sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t dp0002/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dp0002/docker-react npm run test
